name: deploy app

on:
  push:
    branches: master

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        - name: Log in to Docker Hub (if needed)
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: docker build -t shriesannith/practice
      - name: push
        run: docker push shriesannith/practice

  deploy:
  name:
    runs-on: self-hosted
    steps:
      - name: pull
        run: docker pull shriesannith/practice
      - name: run
        run: docker run --name practice-container -d -p 5000:5000 shriesannith/practice
